/* SPDX-License-Identifier: MIT */
/*
 * Minimal Hypervisor.framework interface for QEMU's HVF accelerator: only what
 * QEMU uses, written from the documented ABI. The framework cannot be linked,
 * so every hv_*() call goes through a table filled in with cosmo_dlopen()/cosmo_dlsym().
 */
#ifndef COSMO_HYPERVISOR_H
#define COSMO_HYPERVISOR_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef int32_t hv_return_t;
#define HV_SUCCESS       ((hv_return_t)0)
#define HV_ERROR         ((hv_return_t)0xfae94001)
#define HV_BUSY          ((hv_return_t)0xfae94002)
#define HV_BAD_ARGUMENT  ((hv_return_t)0xfae94003)
#define HV_NO_RESOURCES  ((hv_return_t)0xfae94005)
#define HV_NO_DEVICE     ((hv_return_t)0xfae94006)
#define HV_DENIED        ((hv_return_t)0xfae94007)
#define HV_UNSUPPORTED   ((hv_return_t)0xfae9400f)

typedef uint64_t hv_ipa_t;
typedef uint64_t hv_vcpu_t;
typedef uint64_t hv_memory_flags_t;
typedef struct hv_vm_config_s *hv_vm_config_t;
typedef struct hv_vcpu_config_s *hv_vcpu_config_t;

#define HV_MEMORY_READ   (1ull << 0)
#define HV_MEMORY_WRITE  (1ull << 1)
#define HV_MEMORY_EXEC   (1ull << 2)

typedef uint32_t hv_exit_reason_t;
#define HV_EXIT_REASON_CANCELED         ((hv_exit_reason_t)0)
#define HV_EXIT_REASON_EXCEPTION        ((hv_exit_reason_t)1)
#define HV_EXIT_REASON_VTIMER_ACTIVATED ((hv_exit_reason_t)2)

typedef struct {
    uint64_t syndrome;
    uint64_t virtual_address;
    hv_ipa_t physical_address;
} hv_vcpu_exit_exception_t;

typedef struct {
    hv_exit_reason_t reason;
    hv_vcpu_exit_exception_t exception;
} hv_vcpu_exit_t;

/* 128-bit SIMD&FP register, passed in a vector register by the AAPCS64 */
typedef uint8_t hv_simd_fp_uchar16_t __attribute__((vector_size(16)));

typedef uint32_t hv_reg_t;
typedef uint32_t hv_simd_fp_reg_t;
typedef uint32_t hv_sys_reg_t;
typedef uint32_t hv_feature_reg_t;
typedef uint32_t hv_interrupt_type_t;

enum {
    HV_REG_X0 = 0,
    HV_REG_X1 = 1,
    HV_REG_X2 = 2,
    HV_REG_X3 = 3,
    HV_REG_X4 = 4,
    HV_REG_X5 = 5,
    HV_REG_X6 = 6,
    HV_REG_X7 = 7,
    HV_REG_X8 = 8,
    HV_REG_X9 = 9,
    HV_REG_X10 = 10,
    HV_REG_X11 = 11,
    HV_REG_X12 = 12,
    HV_REG_X13 = 13,
    HV_REG_X14 = 14,
    HV_REG_X15 = 15,
    HV_REG_X16 = 16,
    HV_REG_X17 = 17,
    HV_REG_X18 = 18,
    HV_REG_X19 = 19,
    HV_REG_X20 = 20,
    HV_REG_X21 = 21,
    HV_REG_X22 = 22,
    HV_REG_X23 = 23,
    HV_REG_X24 = 24,
    HV_REG_X25 = 25,
    HV_REG_X26 = 26,
    HV_REG_X27 = 27,
    HV_REG_X28 = 28,
    HV_REG_X29 = 29,
    HV_REG_X30 = 30,
    HV_REG_PC = 31,
    HV_REG_FPCR = 32,
    HV_REG_FPSR = 33,
    HV_REG_CPSR = 34,
};

enum {
    HV_SIMD_FP_REG_Q0 = 0,
    HV_SIMD_FP_REG_Q1 = 1,
    HV_SIMD_FP_REG_Q2 = 2,
    HV_SIMD_FP_REG_Q3 = 3,
    HV_SIMD_FP_REG_Q4 = 4,
    HV_SIMD_FP_REG_Q5 = 5,
    HV_SIMD_FP_REG_Q6 = 6,
    HV_SIMD_FP_REG_Q7 = 7,
    HV_SIMD_FP_REG_Q8 = 8,
    HV_SIMD_FP_REG_Q9 = 9,
    HV_SIMD_FP_REG_Q10 = 10,
    HV_SIMD_FP_REG_Q11 = 11,
    HV_SIMD_FP_REG_Q12 = 12,
    HV_SIMD_FP_REG_Q13 = 13,
    HV_SIMD_FP_REG_Q14 = 14,
    HV_SIMD_FP_REG_Q15 = 15,
    HV_SIMD_FP_REG_Q16 = 16,
    HV_SIMD_FP_REG_Q17 = 17,
    HV_SIMD_FP_REG_Q18 = 18,
    HV_SIMD_FP_REG_Q19 = 19,
    HV_SIMD_FP_REG_Q20 = 20,
    HV_SIMD_FP_REG_Q21 = 21,
    HV_SIMD_FP_REG_Q22 = 22,
    HV_SIMD_FP_REG_Q23 = 23,
    HV_SIMD_FP_REG_Q24 = 24,
    HV_SIMD_FP_REG_Q25 = 25,
    HV_SIMD_FP_REG_Q26 = 26,
    HV_SIMD_FP_REG_Q27 = 27,
    HV_SIMD_FP_REG_Q28 = 28,
    HV_SIMD_FP_REG_Q29 = 29,
    HV_SIMD_FP_REG_Q30 = 30,
    HV_SIMD_FP_REG_Q31 = 31,
};

enum {
    HV_INTERRUPT_TYPE_IRQ = 0,
    HV_INTERRUPT_TYPE_FIQ = 1,
};

enum {
    HV_FEATURE_REG_ID_AA64DFR0_EL1 = 0,
};

/* HV_SYS_REG_* are generated by scripts/lib/headers.sh from QEMU's hvf_sreg_match table */
#include "hvf-sysregs.h"

/*
 * Functions of the framework, resolved at run time. X(return type, name,
 * parameters)
 */
#define HVF_FUNCTIONS(X) \
    X(hv_return_t, hv_vm_create, (hv_vm_config_t config)) \
    X(hv_return_t, hv_vm_map, (void *addr, hv_ipa_t ipa, size_t size, hv_memory_flags_t flags)) \
    X(hv_return_t, hv_vm_unmap, (hv_ipa_t ipa, size_t size)) \
    X(hv_return_t, hv_vm_protect, (hv_ipa_t ipa, size_t size, hv_memory_flags_t flags)) \
    X(hv_vm_config_t, hv_vm_config_create, (void)) \
    X(hv_return_t, hv_vm_config_get_max_ipa_size, (uint32_t *ipa_bit_length)) \
    X(hv_return_t, hv_vm_config_get_default_ipa_size, (uint32_t *ipa_bit_length)) \
    X(hv_return_t, hv_vm_config_set_ipa_size, (hv_vm_config_t config, uint32_t ipa_bit_length)) \
    X(hv_return_t, hv_vcpu_create, (hv_vcpu_t *vcpu, hv_vcpu_exit_t **exit, hv_vcpu_config_t config)) \
    X(hv_return_t, hv_vcpu_destroy, (hv_vcpu_t vcpu)) \
    X(hv_return_t, hv_vcpu_run, (hv_vcpu_t vcpu)) \
    X(hv_return_t, hv_vcpus_exit, (hv_vcpu_t *vcpus, uint32_t vcpu_count)) \
    X(hv_return_t, hv_vcpu_get_reg, (hv_vcpu_t vcpu, hv_reg_t reg, uint64_t *value)) \
    X(hv_return_t, hv_vcpu_set_reg, (hv_vcpu_t vcpu, hv_reg_t reg, uint64_t value)) \
    X(hv_return_t, hv_vcpu_get_simd_fp_reg, (hv_vcpu_t vcpu, hv_simd_fp_reg_t reg, hv_simd_fp_uchar16_t *value)) \
    X(hv_return_t, hv_vcpu_set_simd_fp_reg, (hv_vcpu_t vcpu, hv_simd_fp_reg_t reg, hv_simd_fp_uchar16_t value)) \
    X(hv_return_t, hv_vcpu_get_sys_reg, (hv_vcpu_t vcpu, hv_sys_reg_t reg, uint64_t *value)) \
    X(hv_return_t, hv_vcpu_set_sys_reg, (hv_vcpu_t vcpu, hv_sys_reg_t reg, uint64_t value)) \
    X(hv_return_t, hv_vcpu_set_pending_interrupt, (hv_vcpu_t vcpu, hv_interrupt_type_t type, bool pending)) \
    X(hv_return_t, hv_vcpu_set_trap_debug_exceptions, (hv_vcpu_t vcpu, bool value)) \
    X(hv_return_t, hv_vcpu_set_trap_debug_reg_accesses, (hv_vcpu_t vcpu, bool value)) \
    X(hv_return_t, hv_vcpu_set_vtimer_mask, (hv_vcpu_t vcpu, bool vtimer_is_masked)) \
    X(hv_return_t, hv_vcpu_set_vtimer_offset, (hv_vcpu_t vcpu, uint64_t vtimer_offset)) \
    X(hv_vcpu_config_t, hv_vcpu_config_create, (void)) \
    X(hv_return_t, hv_vcpu_config_get_feature_reg, (hv_vcpu_config_t config, hv_feature_reg_t feature_reg, uint64_t *value))

/* Functions from libSystem that the accelerator also uses */
#define HVF_SYSTEM_FUNCTIONS(X) \
    X(uint64_t, mach_absolute_time, (void)) \
    X(void, os_release, (void *object))

struct HVFDispatch {
    bool loaded;
#define HVF_MEMBER(ret, name, args) ret (*name) args;
    HVF_FUNCTIONS(HVF_MEMBER)
    HVF_SYSTEM_FUNCTIONS(HVF_MEMBER)
#undef HVF_MEMBER
};

extern struct HVFDispatch hvf_dispatch;

/* Loads the framework; false (with a message) when it is not available */
struct Error;
bool hvf_cosmo_load(struct Error **errp);

/* Calls made before hvf_cosmo_load() succeeded are a bug */
void hvf_cosmo_not_loaded(void) __attribute__((noreturn));
static inline struct HVFDispatch *hvf_fns(void)
{
    if (!hvf_dispatch.loaded) {
        hvf_cosmo_not_loaded();
    }
    return &hvf_dispatch;
}

#ifndef HVF_NO_REDIRECT
#define hv_vm_create (hvf_fns()->hv_vm_create)
#define hv_vm_map (hvf_fns()->hv_vm_map)
#define hv_vm_unmap (hvf_fns()->hv_vm_unmap)
#define hv_vm_protect (hvf_fns()->hv_vm_protect)
#define hv_vm_config_create (hvf_fns()->hv_vm_config_create)
#define hv_vm_config_get_max_ipa_size (hvf_fns()->hv_vm_config_get_max_ipa_size)
#define hv_vm_config_get_default_ipa_size (hvf_fns()->hv_vm_config_get_default_ipa_size)
#define hv_vm_config_set_ipa_size (hvf_fns()->hv_vm_config_set_ipa_size)
#define hv_vcpu_create (hvf_fns()->hv_vcpu_create)
#define hv_vcpu_destroy (hvf_fns()->hv_vcpu_destroy)
#define hv_vcpu_run (hvf_fns()->hv_vcpu_run)
#define hv_vcpus_exit (hvf_fns()->hv_vcpus_exit)
#define hv_vcpu_get_reg (hvf_fns()->hv_vcpu_get_reg)
#define hv_vcpu_set_reg (hvf_fns()->hv_vcpu_set_reg)
#define hv_vcpu_get_simd_fp_reg (hvf_fns()->hv_vcpu_get_simd_fp_reg)
#define hv_vcpu_set_simd_fp_reg (hvf_fns()->hv_vcpu_set_simd_fp_reg)
#define hv_vcpu_get_sys_reg (hvf_fns()->hv_vcpu_get_sys_reg)
#define hv_vcpu_set_sys_reg (hvf_fns()->hv_vcpu_set_sys_reg)
#define hv_vcpu_set_pending_interrupt (hvf_fns()->hv_vcpu_set_pending_interrupt)
#define hv_vcpu_set_trap_debug_exceptions (hvf_fns()->hv_vcpu_set_trap_debug_exceptions)
#define hv_vcpu_set_trap_debug_reg_accesses (hvf_fns()->hv_vcpu_set_trap_debug_reg_accesses)
#define hv_vcpu_set_vtimer_mask (hvf_fns()->hv_vcpu_set_vtimer_mask)
#define hv_vcpu_set_vtimer_offset (hvf_fns()->hv_vcpu_set_vtimer_offset)
#define hv_vcpu_config_create (hvf_fns()->hv_vcpu_config_create)
#define hv_vcpu_config_get_feature_reg (hvf_fns()->hv_vcpu_config_get_feature_reg)
#define mach_absolute_time (hvf_fns()->mach_absolute_time)
#define os_release (hvf_fns()->os_release)
#endif /* HVF_NO_REDIRECT */

#endif /* COSMO_HYPERVISOR_H */
